# Copyright (c) 2024-2025, Victor Chavez
# SPDX-License-Identifier: GPL-3.0-or-later
name: Build Zephyr Samples

on:
  push:
  pull_request:

jobs:
  build-read-pd:
    runs-on: ubuntu-22.04
    container: ghcr.io/zephyrproject-rtos/ci:v0.26.2
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains

    strategy:
      matrix:
        include:
          - zephyr_version: "3.7.0"
            board: "esp32"
          - zephyr_version: "3.7.0"
            board: "nrf52833dk_nrf52833"
          - zephyr_version: "4.2.0"
            board: "esp32c3_devkitc"
          - zephyr_version: "4.2.0"
            board: "nrf52833dk"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Initialize Zephyr v${{ matrix.zephyr_version }}
        run: |
          cd /tmp/
          west init --mr=v${{ matrix.zephyr_version }}
          west update -o=--depth=1 -n

      - name: Build read_pd for ${{ matrix.board }} on Zephyr ${{ matrix.zephyr_version }}
        working-directory: /tmp/
        run: |
          build_dir=$GITHUB_WORKSPACE/build/${{ matrix.zephyr_version }}/${{ matrix.board }}
          west build $GITHUB_WORKSPACE/samples/read_pd \
            -b ${{ matrix.board }} \
            --build-dir $build_dir
